name: insane_straps
description: Insane Straps mobile companion app.
publish_to: "none"
version: 2.2.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  app_links: ^6.3.2
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/payment_qr.png
    - assets/insane_app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/insane_app_icon.png"
  image_path_android: "assets/insane_app_icon.png"
  image_path_ios: "assets/insane_app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/insane_app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
